/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Fcfs.Fcfs;
import RoundRobin.RoundRobin;
import Srtf.Srtf;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author Cristian
 */
public class Interfaz extends javax.swing.JFrame {

    public Fcfs fifo = new Fcfs(this);
    public Srtf srtf = new Srtf(this, fifo);
    public RoundRobin round_robin = new RoundRobin(this, srtf);
    int x = 0;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        jTable1.selectAll();
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    public JTextArea getTexto_sistema() {
        return texto_sistema;
    }

    public void setTexto_sistema(JTextArea texto_sistema) {
        this.texto_sistema = texto_sistema;
    }

    public JTextArea getTexto_usuarios() {
        return texto_usuarios;
    }

    public void setTexto_usuarios(JTextArea texto_usuarios) {
        this.texto_usuarios = texto_usuarios;
    }

    public JLabel getTotal_sistema() {
        return total_sistema;
    }

    public void setTotal_sistema(JLabel total_sistema) {
        this.total_sistema = total_sistema;
    }

    public JLabel getTotal_usuarios() {
        return total_usuarios;
    }

    public void setTotal_usuarios(JLabel total_usuarios) {
        this.total_usuarios = total_usuarios;
    }

    public JTextArea getTexto_suspendidos() {
        return texto_suspendidos;
    }

    public void setTexto_suspendidos(JTextArea texto_suspendidos) {
        this.texto_suspendidos = texto_suspendidos;
    }

    public JLabel getTotal_suspendidos() {
        return total_suspendidos;
    }

    public void setTotal_suspendidos(JLabel total_suspendidos) {
        this.total_suspendidos = total_suspendidos;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JLabel getTiempo_real() {
        return tiempo_real;
    }

    public void setTiempo_real(JLabel tiempo_real) {
        this.tiempo_real = tiempo_real;
    }

    public JLabel getCpu_nuevo() {
        return cpu_nuevo;
    }

    public void setCpu_nuevo(JLabel cpu_nuevo) {
        this.cpu_nuevo = cpu_nuevo;
    }

    public JLabel getProcesos_en_ejecucion() {
        return procesos_en_ejecucion;
    }

    public void setProcesos_en_ejecucion(JLabel procesos_en_ejecucion) {
        this.procesos_en_ejecucion = procesos_en_ejecucion;
    }

    public JTextArea getTexto_atendidos() {
        return texto_atendidos;
    }

    public void setTexto_atendidos(JTextArea texto_atendidos) {
        this.texto_atendidos = texto_atendidos;
    }

    public JTextArea getTexto_bloqueados() {
        return texto_bloqueados;
    }

    public void setTexto_bloqueados(JTextArea texto_bloqueados) {
        this.texto_bloqueados = texto_bloqueados;
    }

    public JTextArea getTexto_interactivos() {
        return texto_interactivos;
    }

    public void setTexto_interactivos(JTextArea texto_listos) {
        this.texto_interactivos = texto_listos;
    }

    public JLabel getTiempo_cpu() {
        return tiempo_cpu;
    }

    public void setTiempo_cpu(JLabel tiempo_cpu) {
        this.tiempo_cpu = tiempo_cpu;
    }

    public JLabel getTotal_atendidos() {
        return total_atendidos;
    }

    public void setTotal_atendidos(JLabel total_atendidos) {
        this.total_atendidos = total_atendidos;
    }

    public JLabel getTotal_bloqueados() {
        return total_bloqueados;
    }

    public void setTotal_bloqueados(JLabel total_bloqueados) {
        this.total_bloqueados = total_bloqueados;
    }

    public JLabel getTotal_interactivos() {
        return total_interactivos;
    }

    public void setTotal_interactivos(JLabel total_listos) {
        this.total_interactivos = total_listos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        texto_interactivos = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        total_interactivos = new javax.swing.JLabel();
        cpu_nuevo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        texto_sistema = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        total_sistema = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        tiempo_cpu = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        texto_atendidos = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        total_atendidos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        texto_bloqueados = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        texto_usuarios = new javax.swing.JTextArea();
        jPanel20 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        total_usuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        total_suspendidos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tiempo_real = new javax.swing.JLabel();
        total_bloqueados = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        procesos_en_ejecucion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        texto_suspendidos = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 1365, 740));
        setMinimumSize(new java.awt.Dimension(1365, 740));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel7.setText("Ráfaga ejecutada:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(720, 820, 90, 14);

        jPanel14.setBackground(new java.awt.Color(255, 204, 204));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setLayout(null);

        jScrollPane6.setBackground(new java.awt.Color(255, 0, 0));

        texto_interactivos.setEditable(false);
        texto_interactivos.setColumns(20);
        texto_interactivos.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        texto_interactivos.setRows(5);
        texto_interactivos.setToolTipText("");
        texto_interactivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texto_interactivosKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(texto_interactivos);

        jPanel14.add(jScrollPane6);
        jScrollPane6.setBounds(20, 30, 340, 180);

        jLabel24.setBackground(new java.awt.Color(204, 0, 0));
        jLabel24.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cola2 - Algoritmo SJF [Color Rojo]", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel14.add(jLabel24);
        jLabel24.setBounds(10, 10, 360, 210);

        jPanel19.setBackground(new java.awt.Color(195, 242, 250));
        jPanel19.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel19.setLayout(null);

        jButton5.setText("Agregar Proceso");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton5);
        jButton5.setBounds(0, 0, 130, 23);

        jButton6.setText("Bloquear Proceso");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton6);
        jButton6.setBounds(120, 0, 140, 23);

        jPanel14.add(jPanel19);
        jPanel19.setBounds(10, 220, 260, 30);

        jLabel16.setText("Total Cola2: ");
        jPanel14.add(jLabel16);
        jLabel16.setBounds(280, 230, 61, 14);

        total_interactivos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_interactivos.setText("0");
        jPanel14.add(total_interactivos);
        total_interactivos.setBounds(360, 230, 10, 17);

        jPanel3.add(jPanel14);
        jPanel14.setBounds(0, 510, 380, 254);
        jPanel3.add(cpu_nuevo);
        cpu_nuevo.setBounds(441, 735, 48, 14);

        jLabel5.setText("Ráfaga total:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(850, 810, 64, 30);

        jPanel12.setBackground(new java.awt.Color(255, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(null);

        jScrollPane5.setBackground(new java.awt.Color(255, 0, 0));

        texto_sistema.setEditable(false);
        texto_sistema.setColumns(20);
        texto_sistema.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        texto_sistema.setRows(5);
        texto_sistema.setToolTipText("");
        texto_sistema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texto_sistemaKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(texto_sistema);

        jPanel12.add(jScrollPane5);
        jScrollPane5.setBounds(20, 30, 340, 180);

        jLabel23.setBackground(new java.awt.Color(204, 0, 0));
        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cola1 - Algoritmo ROUND ROBIN [Color Magenta]", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel12.add(jLabel23);
        jLabel23.setBounds(10, 10, 360, 210);

        jPanel18.setBackground(new java.awt.Color(195, 242, 250));
        jPanel18.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel18.setLayout(null);

        jButton3.setText("Agregar Proceso");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton3);
        jButton3.setBounds(0, 0, 130, 23);

        jButton4.setText("Bloquear Proceso");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton4);
        jButton4.setBounds(120, 0, 140, 23);

        jPanel12.add(jPanel18);
        jPanel18.setBounds(10, 220, 260, 30);

        total_sistema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_sistema.setText("0");
        jPanel12.add(total_sistema);
        total_sistema.setBounds(360, 230, 10, 17);

        jLabel9.setText("Total Cola1: ");
        jPanel12.add(jLabel9);
        jLabel9.setBounds(280, 230, 61, 14);

        jPanel3.add(jPanel12);
        jPanel12.setBounds(0, 260, 381, 254);

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Lucida Grande", 1, 25)); // NOI18N
        jLabel40.setText("Proyecto Final - Sistemas Operativos");
        jPanel3.add(jLabel40);
        jLabel40.setBounds(500, 60, 810, 33);
        jPanel3.add(tiempo_cpu);
        tiempo_cpu.setBounds(260, 735, 63, 14);

        jPanel10.setBackground(new java.awt.Color(204, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(null);

        jScrollPane11.setBackground(new java.awt.Color(0, 102, 102));
        jScrollPane11.setAutoscrolls(true);
        jScrollPane11.setEnabled(false);

        texto_atendidos.setEditable(false);
        texto_atendidos.setColumns(20);
        texto_atendidos.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        texto_atendidos.setRows(5);
        texto_atendidos.setToolTipText("");
        jScrollPane11.setViewportView(texto_atendidos);

        jPanel10.add(jScrollPane11);
        jScrollPane11.setBounds(20, 30, 350, 80);

        jLabel29.setBackground(new java.awt.Color(0, 102, 102));
        jLabel29.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel29.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROCESOS FINALIZADOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel10.add(jLabel29);
        jLabel29.setBounds(10, 10, 370, 110);

        jLabel13.setText("Total Finalizados:");
        jPanel10.add(jLabel13);
        jLabel13.setBounds(240, 120, 120, 14);

        total_atendidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_atendidos.setText("0");
        jPanel10.add(total_atendidos);
        total_atendidos.setBounds(360, 120, 27, 17);

        jPanel3.add(jPanel10);
        jPanel10.setBounds(980, 710, 388, 140);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);
        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 0, 1370, 10);

        jScrollPane7.setToolTipText("");
        jScrollPane7.setMinimumSize(new java.awt.Dimension(1080, 23));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"2", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"3", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"4", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"5", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"6", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"7", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"8", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"9", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"10", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"11", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"12", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"13", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"14", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"15", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"16", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"17", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"18", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"19", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"20", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"21", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"22", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"23", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"24", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"25", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "P", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "TE", "TS"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setGridColor(new java.awt.Color(0, 0, 102));
        jTable1.setMaximumSize(new java.awt.Dimension(1086, 416));
        jTable1.setMinimumSize(new java.awt.Dimension(1026, 416));
        jTable1.setPreferredSize(new java.awt.Dimension(2200, 416));
        jScrollPane7.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel3.add(jScrollPane7);
        jScrollPane7.setBounds(410, 170, 960, 240);

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        jScrollPane9.setBackground(new java.awt.Color(0, 204, 204));

        texto_bloqueados.setEditable(false);
        texto_bloqueados.setColumns(20);
        texto_bloqueados.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        texto_bloqueados.setRows(5);
        texto_bloqueados.setToolTipText("");
        jScrollPane9.setViewportView(texto_bloqueados);

        jPanel9.add(jScrollPane9);
        jScrollPane9.setBounds(20, 30, 350, 90);

        jLabel27.setBackground(new java.awt.Color(0, 204, 204));
        jLabel27.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel27.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROCESOS BLOQUEADOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel9.add(jLabel27);
        jLabel27.setBounds(10, 10, 370, 120);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(980, 420, 388, 140);

        jPanel15.setBackground(new java.awt.Color(255, 204, 204));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setLayout(null);

        jScrollPane8.setBackground(new java.awt.Color(255, 0, 0));

        texto_usuarios.setEditable(false);
        texto_usuarios.setColumns(20);
        texto_usuarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        texto_usuarios.setRows(5);
        texto_usuarios.setToolTipText("");
        texto_usuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texto_usuariosKeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(texto_usuarios);

        jPanel15.add(jScrollPane8);
        jScrollPane8.setBounds(20, 30, 340, 180);

        jPanel20.setBackground(new java.awt.Color(195, 242, 250));
        jPanel20.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel20.setLayout(null);

        jButton7.setText("Agregar Proceso");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton7);
        jButton7.setBounds(0, 0, 130, 23);

        jButton8.setText("Bloquear Proceso");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton8);
        jButton8.setBounds(120, 0, 140, 23);

        jPanel15.add(jPanel20);
        jPanel20.setBounds(10, 220, 260, 30);

        jLabel14.setText("Total Cola3: ");
        jPanel15.add(jLabel14);
        jLabel14.setBounds(280, 230, 61, 14);

        total_usuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_usuarios.setText("0");
        jPanel15.add(total_usuarios);
        total_usuarios.setBounds(360, 230, 10, 17);

        jLabel1.setText("Alogritmo FCFS - [Color Amarillo]");
        jPanel15.add(jLabel1);
        jLabel1.setBounds(30, 10, 190, 14);

        jPanel3.add(jPanel15);
        jPanel15.setBounds(0, 10, 381, 254);

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel4.setText("Quantun:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 90, 60, 16);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel18.setText("ProcesosSuspendidos:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 70, 140, 16);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel8.setText("5");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(150, 90, 10, 16);

        total_suspendidos.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        total_suspendidos.setText("0");
        jPanel2.add(total_suspendidos);
        total_suspendidos.setBounds(150, 70, 20, 16);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel3.setText("Tiempo Transcurrido:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 122, 16);

        tiempo_real.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        tiempo_real.setText("0");
        jPanel2.add(tiempo_real);
        tiempo_real.setBounds(150, 10, 24, 16);

        total_bloqueados.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        total_bloqueados.setText("0");
        jPanel2.add(total_bloqueados);
        total_bloqueados.setBounds(150, 50, 20, 16);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel11.setText("Procesos Bloqueados:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 50, 150, 16);

        procesos_en_ejecucion.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        procesos_en_ejecucion.setText("0");
        jPanel2.add(procesos_en_ejecucion);
        procesos_en_ejecucion.setBounds(150, 30, 30, 16);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel6.setText("Proceso en Ejecucion: ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 30, 140, 16);

        jPanel8.add(jPanel2);
        jPanel2.setBounds(10, 30, 170, 120);

        jLabel30.setBackground(new java.awt.Color(0, 0, 255));
        jLabel30.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EJECUCIÓN", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel8.add(jLabel30);
        jLabel30.setBounds(0, 10, 190, 240);

        jLabel31.setBackground(new java.awt.Color(0, 0, 255));
        jLabel31.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel31.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CPU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel8.add(jLabel31);
        jLabel31.setBounds(20, 150, 150, 90);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(null);

        jLabel21.setBackground(new java.awt.Color(0, 204, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel17.add(jLabel21);
        jLabel21.setBounds(10, 10, 110, 40);

        jPanel8.add(jPanel17);
        jPanel17.setBounds(30, 170, 130, 60);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(490, 470, 196, 254);

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(null);

        jScrollPane10.setBackground(new java.awt.Color(255, 153, 51));

        texto_suspendidos.setEditable(false);
        texto_suspendidos.setColumns(20);
        texto_suspendidos.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        texto_suspendidos.setRows(5);
        texto_suspendidos.setToolTipText("");
        jScrollPane10.setViewportView(texto_suspendidos);

        jPanel11.add(jScrollPane10);
        jScrollPane10.setBounds(20, 30, 350, 90);

        jLabel28.setBackground(new java.awt.Color(255, 153, 51));
        jLabel28.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROCESOS SUSPENDIDOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel11.add(jLabel28);
        jLabel28.setBounds(10, 10, 370, 120);

        jPanel3.add(jPanel11);
        jPanel11.setBounds(978, 570, 390, 130);

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(146, 225, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jButton10.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton10.setText("INICIAR");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(0, 0, 120, 25);

        jButton12.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton12.setText("SALIR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(0, 30, 120, 25);

        jPanel6.add(jPanel1);
        jPanel1.setBounds(20, 30, 120, 60);

        jPanel7.setBackground(new java.awt.Color(255, 241, 177));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        jButton13.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton13.setText("INICIAR");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton13);
        jButton13.setBounds(110, 30, 200, 25);

        jButton14.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton14.setText("PAUSAR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton14);
        jButton14.setBounds(110, 60, 200, 25);

        jButton15.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton15.setText("REANUDAR");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton15);
        jButton15.setBounds(110, 90, 200, 25);

        jButton16.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton16.setText("SALIR");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton16);
        jButton16.setBounds(110, 120, 200, 25);

        jLabel15.setBackground(new java.awt.Color(0, 0, 204));
        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel7.add(jLabel15);
        jLabel15.setBounds(20, 10, 300, 150);

        jPanel4.setBackground(new java.awt.Color(146, 225, 238));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);
        jPanel7.add(jPanel4);
        jPanel4.setBounds(110, 30, 200, 120);

        jLabel26.setBackground(new java.awt.Color(0, 0, 204));
        jLabel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel7.add(jLabel26);
        jLabel26.setBounds(20, 10, 300, 150);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(1030, 90, 330, 170);

        jLabel17.setBackground(new java.awt.Color(0, 0, 204));
        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel6.add(jLabel17);
        jLabel17.setBounds(10, 10, 140, 90);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(700, 540, 157, 104);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setText("Diagrama de Gannt");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(780, 130, 167, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1370, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Se agrego un proceso a cola1");
        round_robin.agregar_proceso = true;
        round_robin.agregarProceso();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        round_robin.bandera = true;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        srtf.bandera = true;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Se agrego un proceso a cola2");
        srtf.agregar_proceso = true;
        srtf.agregarProceso();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Se agrego un proceso a cola3");
        fifo.agregar_proceso = true;
        fifo.agregarProceso();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        fifo.bandera = true;
    }//GEN-LAST:event_jButton8ActionPerformed

    private void texto_sistemaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto_sistemaKeyTyped
        // TODO add your handling code here:
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButton10.doClick();
        }
    }//GEN-LAST:event_texto_sistemaKeyTyped

    private void texto_interactivosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto_interactivosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_interactivosKeyTyped

    private void texto_usuariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto_usuariosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_usuariosKeyTyped

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (x == 0) {
            this.jLabel21.setOpaque(true);//rellena de color el label 
            this.jLabel21.setForeground(Color.black);
            this.jButton10.setEnabled(false);
            fifo.setRobin(round_robin);
            round_robin.start();
            this.srtf.start();
            this.srtf.fifo.start();
        } else {
            JOptionPane.showMessageDialog(null, "Imposible comenzar nuevamente");
        }
        x = x + 1;
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpu_nuevo;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel procesos_en_ejecucion;
    private javax.swing.JTextArea texto_atendidos;
    private javax.swing.JTextArea texto_bloqueados;
    private javax.swing.JTextArea texto_interactivos;
    private javax.swing.JTextArea texto_sistema;
    private javax.swing.JTextArea texto_suspendidos;
    private javax.swing.JTextArea texto_usuarios;
    private javax.swing.JLabel tiempo_cpu;
    private javax.swing.JLabel tiempo_real;
    private javax.swing.JLabel total_atendidos;
    private javax.swing.JLabel total_bloqueados;
    private javax.swing.JLabel total_interactivos;
    private javax.swing.JLabel total_sistema;
    private javax.swing.JLabel total_suspendidos;
    private javax.swing.JLabel total_usuarios;
    // End of variables declaration//GEN-END:variables
}
